version: "3.9"

services:
  crawl4ai-service:
    build:
      context: .
    container_name: crawl4ai_microservice
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app         # Mount local code into container
    # command: >
    #   uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
